# python -m torch.distributed.launch --nproc_per_node=2 --master_port=4323 /hy-tmp/optimize_stage3/basicsr/train.py -opt /hy-tmp/optimize_stage3/options/LOL_v2_syn_stage3.yml --launcher pytorch
# export OMP_NUM_THREADS=32
name: LOL_v2_syn_stage3
model_type: codemtnetModel
num_gpu: 2
manual_seed: 1

# dataset and data loader settings
datasets:
  train:
    name: LOL
    type: PairedImageDataset
    dataroot_gt: # ../LOL-v2/Synthetic/Train/Normal
    dataroot_lq: # ../LOL-v2/Synthetic/Train/Low
    filename_tmpl: '{}'
    io_backend:
      type: disk

    in_size: 256
    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1 # 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true
    scale: 1

    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

    geometric_augs: true

  val:
    name: LOL_Test
    type: PairedImageDataset
    dataroot_lq: # ../LOL-v2/Synthetic/Test/Low
    dataroot_gt: # ../LOL-v2/Synthetic/Test/Normal
    io_backend:
      type: disk

    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    scale: 1

# network structures
network_g:
  type: codemtnet
  dim_embd: 256
  n_head: 8
  mamba_layers: 6
  transformer_layers: 2
  codebook_size: 1024
  latent_size: 256
  fuse_encoder_block: [12, 8, 4]
  fuse_generator_block: [10, 13, 16]
  fix_modules: ['dae','mcrb', 'hq_encoder', 'quantize','generator']
  vqgan_path: ~
  img_size: 256
  nf: 64
  ch_mult: [1, 2, 2, 4, 4]
  res_blocks: 2
  d_state: 16
  mlp_ratio: 2


network_vqgan: # this config is needed if no pre-calculated latent
  type: VQAutoEncoder
  img_size: 256
  nf: 64
  ch_mult: [1, 2, 2, 4, 4]
  quantizer: 'nearest'
  codebook_size: 1024

network_d:
  type: VQGANDiscriminator
  nc: 3
  ndf: 64
  n_layers: 4
  model_path: ~

# path
path:
  pretrain_network_hq: # net_g_latest.pth    # do not need optimization
  strict_load_hq: true
  pretrain_network_g: # net_g_latest.pth
  param_key_g: params_ema
  strict_load_g: false
  pretrain_network_d: # net_d_latest.pth
  strict_load_d: false
  resume_state: ~

train:
  use_hq_feat_loss: false
  feat_loss_weight: 1.0
  cross_entropy_loss: false
  entropy_loss_weight: 1.0
  scale_adaptive_gan_weight: 0.1
  fidelity_weight: 1.0

  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [80000]
    restart_weights: [1]
    eta_mins: [0.0000001]

  total_iter: 80000

  warmup_iter: -1  # no warm up
  ema_decay: 0.997

  pixel_opt:
    type: L1Loss
    loss_weight: 5.0
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true

  gan_opt:
    type: GANLoss
    gan_type: vanilla
    loss_weight: !!float 1.0 # adaptive_weighting

  ssim_opt:
    loss_weight: 0.2
    normalize: true

  use_adaptive_weight: true

  disc_weight: 0.2
  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 70000    # maybe? 120001
  manual_seed: 0

# validation settings
val:
  val_freq: !!float 1000    # 2000
  save_img: true

  test_shape: [1, 24, 24, 256]    # shape 600*400 bgr img

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 10    # 100
  save_checkpoint_freq: !!float 5000    # 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29420

find_unused_parameters: true
