# python -m torch.distributed.launch --nproc_per_node=2 --master_port=4323 /hy-tmp/optimize_stage3/basicsr/train.py -opt /hy-tmp/optimize_stage3/options/LOL_v2_real_stage3.yml --launcher pytorch
# export OMP_NUM_THREADS=32
name: my_stage3
model_type: CodeFormerModel
num_gpu: 1
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: LOL
    type: PairedImageDataset
    dataroot_gt: /home/dell/桌面/drh/LOL-v2/Real_captured/Train/Normal
    dataroot_lq: /home/dell/桌面/drh/LOL-v2/Real_captured/Train/Low
    filename_tmpl: '{}'
    io_backend:
      type: disk

    in_size: 256
    gt_size: 256

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    scale: 1
    geometric_augs: true

  val:
    name: LOL_Test
    type: PairedImageDataset
    dataroot_lq: /home/dell/桌面/drh/LOL-v2/Real_captured/Test/Low
    dataroot_gt: /home/dell/桌面/drh/LOL-v2/Real_captured/Test/Normal
    io_backend:
      type: disk
    scale: 1

# network structures
network_g:
  type: CodeFormer
  dim_embd: 256
  n_head: 8
  mamba_layers: 6
  transformer_layers: 2
  codebook_size: 1024
  latent_size: 256
  fuse_encoder_block: [12, 8, 4]
  fuse_generator_block: [10, 13, 16]
  fix_modules: ['dae','macr', 'hq_encoder', 'quantize','generator']
  vqgan_path: ~
  img_size: 256
  nf: 64
  ch_mult: [1, 2, 2, 4, 4]
  res_blocks: 2
  d_state: 32
  mlp_ratio: 4
  L: 32
  hidden_list: [128, 128, 128]


network_vqgan: # this config is needed if no pre-calculated latent
  type: VQAutoEncoder
  img_size: 256
  nf: 64
  ch_mult: [1, 2, 2, 4, 4]
  quantizer: 'nearest'
  codebook_size: 1024

network_d:
  type: VQGANDiscriminator
  nc: 3
  ndf: 64
  n_layers: 4
  model_path: ~

# path
path:
  pretrain_network_hq: /home/dell/桌面/drh/retry_no_norm/experiments/best_lolv2_real/20241008_193323_VQGAN_FineTune_Lol_v2_real/models/net_g_latest.pth
  strict_load_hq: true
  pretrain_network_g: /home/dell/桌面/drh/retry_no_norm/experiments/best_lolv2_real/stage2/models/net_g_50000.pth
  param_key_g: params_ema
  strict_load_g: false
  resume_state: ~

train:
  use_hq_feat_loss: false
  feat_loss_weight: 0.2
  cross_entropy_loss: false
  entropy_loss_weight: 2.0
  fidelity_weight: 1.0

  optim_g:
    type: Adam
    lr: !!float 1e-4    # 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [70000, 75000, 50000]    # [70000, 75000, 50000]
    restart_weights: [0.5, 1, 1]  # [1, 1, 1]
    eta_mins: [0.00005, 0.00001, 0.00001]    # [0.0001, 0.00005, 0.00001]

  total_iter: 195000

  warmup_iter: -1
  ema_decay: 0.997

  pixel_opt:
    type: L1Loss
    loss_weight: 0.1
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 0.1
    use_input_norm: true
    range_norm: true

  ssim_opt:
    loss_weight: 1.0
    normalize: true

  use_adaptive_weight: true
  net_g_start_iter: 0
  manual_seed: 0

# validation settings
val:
  val_freq: !!float 2000    # 2000
  save_img: true

  test_shape: [1, 25, 38, 256]    # shape 600*400 bgr img

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 10    # 100
  save_checkpoint_freq: !!float 5000    # 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29420

find_unused_parameters: true
