name: VQGAN_Pretrain
model_type: VQGANModel
num_gpu: 1
manual_seed: 0

datasets:
  train:
    name: HighResolution
    type: HighQualityDataset
    dataroot_gt: /home/dell/桌面/drh/DIV2K_train_HR
    filename_tmpl: '{}'
    io_backend:
      type: disk

    in_size: 256
    gt_size: 256
    use_hfilp: true

    num_worker_per_gpu: 64
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100

    prefetch_mode: cuda
    num_prefetch_queue: 4

    pin_memory: true

  val:
     name: LOL_Test
     type: PairedImageDataset
     dataroot_lq: /home/dell/桌面/drh/LOL-v1/eval15/high
     dataroot_gt: /home/dell/桌面/drh/LOL-v1/eval15/high
     io_backend:
       type: disk
     scale: 1

network_g:
  type: VQAutoEncoder
  img_size: 256
  nf: 64
  ch_mult: [1, 2, 2, 4, 4]
  quantizer: 'nearest'
  codebook_size: 1024

network_d:
  type: VQGANDiscriminator
  nc: 3
  ndf: 64

# path
path:
  pretrain_network_g:
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d:
  strict_load_d: true
  resume_state:

train:
  optim_g:
    type: Adam
    lr: !!float 4e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1600000]
    restart_weights: [1]
    eta_min: !!float 6e-5 # no lr reduce in official vqgan code

  total_iter: 1600000

  warmup_iter: -1  # no warm up
  ema_decay: 0.995 # GFPGAN: 0.5**(32 / (10 * 1000) == 0.998; Unleashing: 0.995

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true

  gan_opt:
    type: GANLoss
    gan_type: hinge
    loss_weight: !!float 1.0 # adaptive_weighting

  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 30001
#  net_d_start_iter: 20

  manual_seed: 0

# validation settings
val:
  val_freq: !!float 5e3
#  val_freq: !!float 100
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29411

find_unused_parameters: false

